// Code generated by jig; DO NOT EDIT.

//go:generate jig

package gio

import (
	"fmt"
	"sync"

	"gioui.org/io/event"
	"github.com/reactivego/scheduler"
	"github.com/reactivego/subscriber"
)

//jig:name Scheduler

// Scheduler is used to schedule tasks to support subscribing and observing.
type Scheduler = scheduler.Scheduler

//jig:name Subscriber

// Subscriber is an interface that can be passed in when subscribing to an
// Observable. It allows a set of observable subscriptions to be canceled
// from a single subscriber at the root of the subscription tree.
type Subscriber = subscriber.Subscriber

//jig:name FrameEventObserver

// FrameEventObserver is a function that gets called whenever the Observable has
// something to report. The next argument is the item value that is only
// valid when the done argument is false. When done is true and the err
// argument is not nil, then the Observable has terminated with an error.
// When done is true and the err argument is nil, then the Observable has
// completed normally.
type FrameEventObserver func(next FrameEvent, err error, done bool)

//jig:name ObservableFrameEvent

// ObservableFrameEvent is a function taking an Observer, Scheduler and Subscriber.
// Calling it will subscribe the Observer to events from the Observable.
type ObservableFrameEvent func(FrameEventObserver, Scheduler, Subscriber)

//jig:name KeyEventObserver

// KeyEventObserver is a function that gets called whenever the Observable has
// something to report. The next argument is the item value that is only
// valid when the done argument is false. When done is true and the err
// argument is not nil, then the Observable has terminated with an error.
// When done is true and the err argument is nil, then the Observable has
// completed normally.
type KeyEventObserver func(next KeyEvent, err error, done bool)

//jig:name ObservableKeyEvent

// ObservableKeyEvent is a function taking an Observer, Scheduler and Subscriber.
// Calling it will subscribe the Observer to events from the Observable.
type ObservableKeyEvent func(KeyEventObserver, Scheduler, Subscriber)

//jig:name PointerEventObserver

// PointerEventObserver is a function that gets called whenever the Observable has
// something to report. The next argument is the item value that is only
// valid when the done argument is false. When done is true and the err
// argument is not nil, then the Observable has terminated with an error.
// When done is true and the err argument is nil, then the Observable has
// completed normally.
type PointerEventObserver func(next PointerEvent, err error, done bool)

//jig:name ObservablePointerEvent

// ObservablePointerEvent is a function taking an Observer, Scheduler and Subscriber.
// Calling it will subscribe the Observer to events from the Observable.
type ObservablePointerEvent func(PointerEventObserver, Scheduler, Subscriber)

//jig:name CallOpObserver

// CallOpObserver is a function that gets called whenever the Observable has
// something to report. The next argument is the item value that is only
// valid when the done argument is false. When done is true and the err
// argument is not nil, then the Observable has terminated with an error.
// When done is true and the err argument is nil, then the Observable has
// completed normally.
type CallOpObserver func(next CallOp, err error, done bool)

//jig:name ObservableCallOp

// ObservableCallOp is a function taking an Observer, Scheduler and Subscriber.
// Calling it will subscribe the Observer to events from the Observable.
type ObservableCallOp func(CallOpObserver, Scheduler, Subscriber)

//jig:name ClickEventObserver

// ClickEventObserver is a function that gets called whenever the Observable has
// something to report. The next argument is the item value that is only
// valid when the done argument is false. When done is true and the err
// argument is not nil, then the Observable has terminated with an error.
// When done is true and the err argument is nil, then the Observable has
// completed normally.
type ClickEventObserver func(next ClickEvent, err error, done bool)

//jig:name ObservableClickEvent

// ObservableClickEvent is a function taking an Observer, Scheduler and Subscriber.
// Calling it will subscribe the Observer to events from the Observable.
type ObservableClickEvent func(ClickEventObserver, Scheduler, Subscriber)

//jig:name ContextEventObserver

// ContextEventObserver is a function that gets called whenever the Observable has
// something to report. The next argument is the item value that is only
// valid when the done argument is false. When done is true and the err
// argument is not nil, then the Observable has terminated with an error.
// When done is true and the err argument is nil, then the Observable has
// completed normally.
type ContextEventObserver func(next ContextEvent, err error, done bool)

//jig:name ObservableContextEvent

// ObservableContextEvent is a function taking an Observer, Scheduler and Subscriber.
// Calling it will subscribe the Observer to events from the Observable.
type ObservableContextEvent func(ContextEventObserver, Scheduler, Subscriber)

//jig:name EditEventObserver

// EditEventObserver is a function that gets called whenever the Observable has
// something to report. The next argument is the item value that is only
// valid when the done argument is false. When done is true and the err
// argument is not nil, then the Observable has terminated with an error.
// When done is true and the err argument is nil, then the Observable has
// completed normally.
type EditEventObserver func(next EditEvent, err error, done bool)

//jig:name ObservableEditEvent

// ObservableEditEvent is a function taking an Observer, Scheduler and Subscriber.
// Calling it will subscribe the Observer to events from the Observable.
type ObservableEditEvent func(EditEventObserver, Scheduler, Subscriber)

//jig:name FocusEventObserver

// FocusEventObserver is a function that gets called whenever the Observable has
// something to report. The next argument is the item value that is only
// valid when the done argument is false. When done is true and the err
// argument is not nil, then the Observable has terminated with an error.
// When done is true and the err argument is nil, then the Observable has
// completed normally.
type FocusEventObserver func(next FocusEvent, err error, done bool)

//jig:name ObservableFocusEvent

// ObservableFocusEvent is a function taking an Observer, Scheduler and Subscriber.
// Calling it will subscribe the Observer to events from the Observable.
type ObservableFocusEvent func(FocusEventObserver, Scheduler, Subscriber)

//jig:name Subscription

// Subscription is an alias for the subscriber.Subscription interface type.
type Subscription = subscriber.Subscription

//jig:name FromChanFrameEvent

// FromChanFrameEvent creates an ObservableFrameEvent from a Go channel of FrameEvent values.
// It's not possible for the code feeding into the channel to send an error.
// The feeding code can send nil or more FrameEvent items and then closing the
// channel will be seen as completion.
func FromChanFrameEvent(ch <-chan FrameEvent) ObservableFrameEvent {
	observable := func(observe FrameEventObserver, scheduler Scheduler, subscriber Subscriber) {
		cancel := make(chan struct{})
		runner := scheduler.ScheduleRecursive(func(self func()) {
			if !subscriber.Subscribed() {
				return
			}
			select {
			case next, ok := <-ch:
				if !subscriber.Subscribed() {
					return
				}
				if ok {
					observe(next, nil, false)
					if !subscriber.Subscribed() {
						return
					}
					self()
				} else {
					var zero FrameEvent
					observe(zero, nil, true)
				}
			case <-cancel:
				return
			}
		})
		subscriber.OnUnsubscribe(func() {
			runner.Cancel()
			close(cancel)
		})
	}
	return observable
}

//jig:name DeferKeyEvent

// DeferKeyEvent does not create the ObservableKeyEvent until the observer subscribes.
// It creates a fresh ObservableKeyEvent for each subscribing observer. Use it to
// create observables that maintain separate state per subscription.
func DeferKeyEvent(factory func() ObservableKeyEvent) ObservableKeyEvent {
	observable := func(observe KeyEventObserver, scheduler Scheduler, subscriber Subscriber) {
		factory()(observe, scheduler, subscriber)
	}
	return observable
}

//jig:name FromChanKeyEvent

// FromChanKeyEvent creates an ObservableKeyEvent from a Go channel of KeyEvent values.
// It's not possible for the code feeding into the channel to send an error.
// The feeding code can send nil or more KeyEvent items and then closing the
// channel will be seen as completion.
func FromChanKeyEvent(ch <-chan KeyEvent) ObservableKeyEvent {
	observable := func(observe KeyEventObserver, scheduler Scheduler, subscriber Subscriber) {
		cancel := make(chan struct{})
		runner := scheduler.ScheduleRecursive(func(self func()) {
			if !subscriber.Subscribed() {
				return
			}
			select {
			case next, ok := <-ch:
				if !subscriber.Subscribed() {
					return
				}
				if ok {
					observe(next, nil, false)
					if !subscriber.Subscribed() {
						return
					}
					self()
				} else {
					var zero KeyEvent
					observe(zero, nil, true)
				}
			case <-cancel:
				return
			}
		})
		subscriber.OnUnsubscribe(func() {
			runner.Cancel()
			close(cancel)
		})
	}
	return observable
}

//jig:name FromChanPointerEvent

// FromChanPointerEvent creates an ObservablePointerEvent from a Go channel of PointerEvent values.
// It's not possible for the code feeding into the channel to send an error.
// The feeding code can send nil or more PointerEvent items and then closing the
// channel will be seen as completion.
func FromChanPointerEvent(ch <-chan PointerEvent) ObservablePointerEvent {
	observable := func(observe PointerEventObserver, scheduler Scheduler, subscriber Subscriber) {
		cancel := make(chan struct{})
		runner := scheduler.ScheduleRecursive(func(self func()) {
			if !subscriber.Subscribed() {
				return
			}
			select {
			case next, ok := <-ch:
				if !subscriber.Subscribed() {
					return
				}
				if ok {
					observe(next, nil, false)
					if !subscriber.Subscribed() {
						return
					}
					self()
				} else {
					var zero PointerEvent
					observe(zero, nil, true)
				}
			case <-cancel:
				return
			}
		})
		subscriber.OnUnsubscribe(func() {
			runner.Cancel()
			close(cancel)
		})
	}
	return observable
}

//jig:name DeferClickEvent

// DeferClickEvent does not create the ObservableClickEvent until the observer subscribes.
// It creates a fresh ObservableClickEvent for each subscribing observer. Use it to
// create observables that maintain separate state per subscription.
func DeferClickEvent(factory func() ObservableClickEvent) ObservableClickEvent {
	observable := func(observe ClickEventObserver, scheduler Scheduler, subscriber Subscriber) {
		factory()(observe, scheduler, subscriber)
	}
	return observable
}

//jig:name FromChanClickEvent

// FromChanClickEvent creates an ObservableClickEvent from a Go channel of ClickEvent values.
// It's not possible for the code feeding into the channel to send an error.
// The feeding code can send nil or more ClickEvent items and then closing the
// channel will be seen as completion.
func FromChanClickEvent(ch <-chan ClickEvent) ObservableClickEvent {
	observable := func(observe ClickEventObserver, scheduler Scheduler, subscriber Subscriber) {
		cancel := make(chan struct{})
		runner := scheduler.ScheduleRecursive(func(self func()) {
			if !subscriber.Subscribed() {
				return
			}
			select {
			case next, ok := <-ch:
				if !subscriber.Subscribed() {
					return
				}
				if ok {
					observe(next, nil, false)
					if !subscriber.Subscribed() {
						return
					}
					self()
				} else {
					var zero ClickEvent
					observe(zero, nil, true)
				}
			case <-cancel:
				return
			}
		})
		subscriber.OnUnsubscribe(func() {
			runner.Cancel()
			close(cancel)
		})
	}
	return observable
}

//jig:name DeferEditEvent

// DeferEditEvent does not create the ObservableEditEvent until the observer subscribes.
// It creates a fresh ObservableEditEvent for each subscribing observer. Use it to
// create observables that maintain separate state per subscription.
func DeferEditEvent(factory func() ObservableEditEvent) ObservableEditEvent {
	observable := func(observe EditEventObserver, scheduler Scheduler, subscriber Subscriber) {
		factory()(observe, scheduler, subscriber)
	}
	return observable
}

//jig:name FromChanEditEvent

// FromChanEditEvent creates an ObservableEditEvent from a Go channel of EditEvent values.
// It's not possible for the code feeding into the channel to send an error.
// The feeding code can send nil or more EditEvent items and then closing the
// channel will be seen as completion.
func FromChanEditEvent(ch <-chan EditEvent) ObservableEditEvent {
	observable := func(observe EditEventObserver, scheduler Scheduler, subscriber Subscriber) {
		cancel := make(chan struct{})
		runner := scheduler.ScheduleRecursive(func(self func()) {
			if !subscriber.Subscribed() {
				return
			}
			select {
			case next, ok := <-ch:
				if !subscriber.Subscribed() {
					return
				}
				if ok {
					observe(next, nil, false)
					if !subscriber.Subscribed() {
						return
					}
					self()
				} else {
					var zero EditEvent
					observe(zero, nil, true)
				}
			case <-cancel:
				return
			}
		})
		subscriber.OnUnsubscribe(func() {
			runner.Cancel()
			close(cancel)
		})
	}
	return observable
}

//jig:name DeferFocusEvent

// DeferFocusEvent does not create the ObservableFocusEvent until the observer subscribes.
// It creates a fresh ObservableFocusEvent for each subscribing observer. Use it to
// create observables that maintain separate state per subscription.
func DeferFocusEvent(factory func() ObservableFocusEvent) ObservableFocusEvent {
	observable := func(observe FocusEventObserver, scheduler Scheduler, subscriber Subscriber) {
		factory()(observe, scheduler, subscriber)
	}
	return observable
}

//jig:name FromChanFocusEvent

// FromChanFocusEvent creates an ObservableFocusEvent from a Go channel of FocusEvent values.
// It's not possible for the code feeding into the channel to send an error.
// The feeding code can send nil or more FocusEvent items and then closing the
// channel will be seen as completion.
func FromChanFocusEvent(ch <-chan FocusEvent) ObservableFocusEvent {
	observable := func(observe FocusEventObserver, scheduler Scheduler, subscriber Subscriber) {
		cancel := make(chan struct{})
		runner := scheduler.ScheduleRecursive(func(self func()) {
			if !subscriber.Subscribed() {
				return
			}
			select {
			case next, ok := <-ch:
				if !subscriber.Subscribed() {
					return
				}
				if ok {
					observe(next, nil, false)
					if !subscriber.Subscribed() {
						return
					}
					self()
				} else {
					var zero FocusEvent
					observe(zero, nil, true)
				}
			case <-cancel:
				return
			}
		})
		subscriber.OnUnsubscribe(func() {
			runner.Cancel()
			close(cancel)
		})
	}
	return observable
}

//jig:name GoroutineScheduler

func GoroutineScheduler() Scheduler {
	return scheduler.Goroutine
}

//jig:name MakeTrampolineScheduler

func MakeTrampolineScheduler() Scheduler {
	return scheduler.MakeTrampoline()
}

//jig:name PrintlnFrameEvent

func PrintlnFrameEvent(a ...interface{}) FrameEventObserver {
	observer := func(next FrameEvent, err error, done bool) {
		if !done {
			fmt.Println(append(a, next)...)
		}
	}
	return observer
}

//jig:name FromCallOp

// FromCallOp creates an ObservableCallOp from multiple CallOp values passed in.
func FromCallOp(slice ...CallOp) ObservableCallOp {
	observable := func(observe CallOpObserver, scheduler Scheduler, subscriber Subscriber) {
		i := 0
		runner := scheduler.ScheduleRecursive(func(self func()) {
			if subscriber.Subscribed() {
				if i < len(slice) {
					observe(slice[i], nil, false)
					if subscriber.Subscribed() {
						i++
						self()
					}
				} else {
					var zero CallOp
					observe(zero, nil, true)
				}
			}
		})
		subscriber.OnUnsubscribe(runner.Cancel)
	}
	return observable
}

//jig:name JustCallOp

// JustCallOp creates an ObservableCallOp that emits a particular item.
func JustCallOp(element CallOp) ObservableCallOp {
	observable := func(observe CallOpObserver, scheduler Scheduler, subscriber Subscriber) {
		runner := scheduler.Schedule(func() {
			if subscriber.Subscribed() {
				observe(element, nil, false)
			}
			if subscriber.Subscribed() {
				var zero CallOp
				observe(zero, nil, true)
			}
		})
		subscriber.OnUnsubscribe(runner.Cancel)
	}
	return observable
}

//jig:name CallOpSlice

type CallOpSlice = []CallOp

//jig:name ObservableObservableCallOp_CombineLatestAll

// CombineLatestAll flattens a higher order observable
// (e.g. ObservableObservableCallOp) by subscribing to
// all emitted observables (ie. ObservableCallOp entries) until the source
// completes. It will then wait for all of the subscribed ObservableCallOps
// to emit before emitting the first slice. Whenever any of the subscribed
// observables emits, a new slice will be emitted containing all the latest
// value.
func (o ObservableObservableCallOp) CombineLatestAll() ObservableCallOpSlice {
	observable := func(observe CallOpSliceObserver, subscribeOn Scheduler, subscriber Subscriber) {
		observables := []ObservableCallOp(nil)
		var observers struct {
			sync.Mutex
			assigned	[]bool
			values		[]CallOp
			initialized	int
			active		int
		}
		makeObserver := func(index int) CallOpObserver {
			observer := func(next CallOp, err error, done bool) {
				observers.Lock()
				defer observers.Unlock()
				if observers.active > 0 {
					switch {
					case !done:
						if !observers.assigned[index] {
							observers.assigned[index] = true
							observers.initialized++
						}
						observers.values[index] = next
						if observers.initialized == len(observers.values) {
							observe(observers.values, nil, false)
						}
					case err != nil:
						observers.active = 0
						var zero []CallOp
						observe(zero, err, true)
					default:
						if observers.active--; observers.active == 0 {
							var zero []CallOp
							observe(zero, nil, true)
						}
					}
				}
			}
			return observer
		}

		observer := func(next ObservableCallOp, err error, done bool) {
			switch {
			case !done:
				observables = append(observables, next)
			case err != nil:
				var zero []CallOp
				observe(zero, err, true)
			default:
				subscribeOn.Schedule(func() {
					if subscriber.Subscribed() {
						numObservables := len(observables)
						observers.assigned = make([]bool, numObservables)
						observers.values = make([]CallOp, numObservables)
						observers.active = numObservables
						for i, v := range observables {
							if !subscriber.Subscribed() {
								return
							}
							v(makeObserver(i), subscribeOn, subscriber)
						}
					}
				})
			}
		}
		o(observer, subscribeOn, subscriber)
	}
	return observable
}

//jig:name CombineLatestCallOp

// CombineLatest will subscribe to all ObservableCallOps. It will then wait for
// all of them to emit before emitting the first slice. Whenever any of the
// subscribed observables emits, a new slice will be emitted containing all
// the latest value.
func CombineLatestCallOp(observables ...ObservableCallOp) ObservableCallOpSlice {
	return FromObservableCallOp(observables...).CombineLatestAll()
}

//jig:name DeferCallOp

// DeferCallOp does not create the ObservableCallOp until the observer subscribes.
// It creates a fresh ObservableCallOp for each subscribing observer. Use it to
// create observables that maintain separate state per subscription.
func DeferCallOp(factory func() ObservableCallOp) ObservableCallOp {
	observable := func(observe CallOpObserver, scheduler Scheduler, subscriber Subscriber) {
		factory()(observe, scheduler, subscriber)
	}
	return observable
}

//jig:name CallOpSliceObserver

// CallOpSliceObserver is a function that gets called whenever the Observable has
// something to report. The next argument is the item value that is only
// valid when the done argument is false. When done is true and the err
// argument is not nil, then the Observable has terminated with an error.
// When done is true and the err argument is nil, then the Observable has
// completed normally.
type CallOpSliceObserver func(next CallOpSlice, err error, done bool)

//jig:name ObservableCallOpSlice

// ObservableCallOpSlice is a function taking an Observer, Scheduler and Subscriber.
// Calling it will subscribe the Observer to events from the Observable.
type ObservableCallOpSlice func(CallOpSliceObserver, Scheduler, Subscriber)

//jig:name EventObserver

// EventObserver is a function that gets called whenever the Observable has
// something to report. The next argument is the item value that is only
// valid when the done argument is false. When done is true and the err
// argument is not nil, then the Observable has terminated with an error.
// When done is true and the err argument is nil, then the Observable has
// completed normally.
type EventObserver func(next event.Event, err error, done bool)

//jig:name ObservableEvent

// ObservableEvent is a function taking an Observer, Scheduler and Subscriber.
// Calling it will subscribe the Observer to events from the Observable.
type ObservableEvent func(EventObserver, Scheduler, Subscriber)

//jig:name FromChanEvent

// FromChanEvent creates an ObservableEvent from a Go channel of event.Event values.
// It's not possible for the code feeding into the channel to send an error.
// The feeding code can send nil or more event.Event items and then closing the
// channel will be seen as completion.
func FromChanEvent(ch <-chan event.Event) ObservableEvent {
	observable := func(observe EventObserver, scheduler Scheduler, subscriber Subscriber) {
		cancel := make(chan struct{})
		runner := scheduler.ScheduleRecursive(func(self func()) {
			if !subscriber.Subscribed() {
				return
			}
			select {
			case next, ok := <-ch:
				if !subscriber.Subscribed() {
					return
				}
				if ok {
					observe(next, nil, false)
					if !subscriber.Subscribed() {
						return
					}
					self()
				} else {
					var zero event.Event
					observe(zero, nil, true)
				}
			case <-cancel:
				return
			}
		})
		subscriber.OnUnsubscribe(func() {
			runner.Cancel()
			close(cancel)
		})
	}
	return observable
}

//jig:name Slice

type Slice = []interface{}

//jig:name ObservableCallOpObserver

// ObservableCallOpObserver is a function that gets called whenever the Observable has
// something to report. The next argument is the item value that is only
// valid when the done argument is false. When done is true and the err
// argument is not nil, then the Observable has terminated with an error.
// When done is true and the err argument is nil, then the Observable has
// completed normally.
type ObservableCallOpObserver func(next ObservableCallOp, err error, done bool)

//jig:name ObservableObservableCallOp

// ObservableObservableCallOp is a function taking an Observer, Scheduler and Subscriber.
// Calling it will subscribe the Observer to events from the Observable.
type ObservableObservableCallOp func(ObservableCallOpObserver, Scheduler, Subscriber)

//jig:name ObservableCallOp_CombineLatestWith

// CombineLatestWith will subscribe to its ObservableCallOp and all other
// ObservableCallOps passed in. It will then wait for all of the ObservableBars
// to emit before emitting the first slice. Whenever any of the subscribed
// observables emits, a new slice will be emitted containing all the latest
// value.
func (o ObservableCallOp) CombineLatestWith(other ...ObservableCallOp) ObservableCallOpSlice {
	return FromObservableCallOp(append([]ObservableCallOp{o}, other...)...).CombineLatestAll()
}

//jig:name ObservableFrameEvent_Subscribe

// Subscribe operates upon the emissions and notifications from an Observable.
// This method returns a Subscription.
// Subscribe uses a trampoline scheduler created with scheduler.MakeTrampoline().
func (o ObservableFrameEvent) Subscribe(observe FrameEventObserver, schedulers ...Scheduler) Subscription {
	subscriber := subscriber.New()
	schedulers = append(schedulers, scheduler.MakeTrampoline())
	observer := func(next FrameEvent, err error, done bool) {
		if !done {
			observe(next, err, done)
		} else {
			var zero FrameEvent
			observe(zero, err, true)
			subscriber.Done(err)
		}
	}
	if !schedulers[0].IsConcurrent() {
		subscriber.OnWait(schedulers[0].Wait)
	}
	o(observer, schedulers[0], subscriber)
	return subscriber
}

//jig:name ObservableCallOpSlice_MapCallOp

// MapCallOp transforms the items emitted by an ObservableCallOpSlice by applying a
// function to each item.
func (o ObservableCallOpSlice) MapCallOp(project func(CallOpSlice) CallOp) ObservableCallOp {
	observable := func(observe CallOpObserver, subscribeOn Scheduler, subscriber Subscriber) {
		observer := func(next CallOpSlice, err error, done bool) {
			var mapped CallOp
			if !done {
				mapped = project(next)
			}
			observe(mapped, err, done)
		}
		o(observer, subscribeOn, subscriber)
	}
	return observable
}

//jig:name FromCallOpSlice

// FromCallOpSlice creates an ObservableCallOpSlice from multiple CallOpSlice values passed in.
func FromCallOpSlice(slice ...CallOpSlice) ObservableCallOpSlice {
	observable := func(observe CallOpSliceObserver, scheduler Scheduler, subscriber Subscriber) {
		i := 0
		runner := scheduler.ScheduleRecursive(func(self func()) {
			if subscriber.Subscribed() {
				if i < len(slice) {
					observe(slice[i], nil, false)
					if subscriber.Subscribed() {
						i++
						self()
					}
				} else {
					var zero CallOpSlice
					observe(zero, nil, true)
				}
			}
		})
		subscriber.OnUnsubscribe(runner.Cancel)
	}
	return observable
}

//jig:name ObservableCallOpSlice_ConcatWith

// ConcatWith emits the emissions from two or more ObservableCallOpSlices without interleaving them.
func (o ObservableCallOpSlice) ConcatWith(other ...ObservableCallOpSlice) ObservableCallOpSlice {
	if len(other) == 0 {
		return o
	}
	observable := func(observe CallOpSliceObserver, subscribeOn Scheduler, subscriber Subscriber) {
		var (
			observables	= append([]ObservableCallOpSlice{}, other...)
			observer	CallOpSliceObserver
		)
		observer = func(next CallOpSlice, err error, done bool) {
			if !done || err != nil {
				observe(next, err, done)
			} else {
				if len(observables) == 0 {
					var zero CallOpSlice
					observe(zero, nil, true)
				} else {
					o := observables[0]
					observables = observables[1:]
					o(observer, subscribeOn, subscriber)
				}
			}
		}
		o(observer, subscribeOn, subscriber)
	}
	return observable
}

//jig:name ObservableCallOpSlice_StartWith

// StartWith returns an observable that, at the moment of subscription, will
// synchronously emit all values provided to this operator, then subscribe to
// the source and mirror all of its emissions to subscribers.
func (o ObservableCallOpSlice) StartWith(values ...CallOpSlice) ObservableCallOpSlice {
	return FromCallOpSlice(values...).ConcatWith(o)
}

//jig:name Observer

// Observer is a function that gets called whenever the Observable has
// something to report. The next argument is the item value that is only
// valid when the done argument is false. When done is true and the err
// argument is not nil, then the Observable has terminated with an error.
// When done is true and the err argument is nil, then the Observable has
// completed normally.
type Observer func(next interface{}, err error, done bool)

//jig:name Observable

// Observable is a function taking an Observer, Scheduler and Subscriber.
// Calling it will subscribe the Observer to events from the Observable.
type Observable func(Observer, Scheduler, Subscriber)

//jig:name ObservableEvent_AsObservable

// AsObservable turns a typed ObservableEvent into an Observable of interface{}.
func (o ObservableEvent) AsObservable() Observable {
	observable := func(observe Observer, subscribeOn Scheduler, subscriber Subscriber) {
		observer := func(next event.Event, err error, done bool) {
			observe(interface{}(next), err, done)
		}
		o(observer, subscribeOn, subscriber)
	}
	return observable
}

//jig:name FromObservableCallOp

// FromObservableCallOp creates an ObservableObservableCallOp from multiple ObservableCallOp values passed in.
func FromObservableCallOp(slice ...ObservableCallOp) ObservableObservableCallOp {
	observable := func(observe ObservableCallOpObserver, scheduler Scheduler, subscriber Subscriber) {
		i := 0
		runner := scheduler.ScheduleRecursive(func(self func()) {
			if subscriber.Subscribed() {
				if i < len(slice) {
					observe(slice[i], nil, false)
					if subscriber.Subscribed() {
						i++
						self()
					}
				} else {
					var zero ObservableCallOp
					observe(zero, nil, true)
				}
			}
		})
		subscriber.OnUnsubscribe(runner.Cancel)
	}
	return observable
}

//jig:name ObservableCallOpSlice_Map

// Map transforms the items emitted by an ObservableCallOpSlice by applying a
// function to each item.
func (o ObservableCallOpSlice) Map(project func(CallOpSlice) interface{}) Observable {
	observable := func(observe Observer, subscribeOn Scheduler, subscriber Subscriber) {
		observer := func(next CallOpSlice, err error, done bool) {
			var mapped interface{}
			if !done {
				mapped = project(next)
			}
			observe(mapped, err, done)
		}
		o(observer, subscribeOn, subscriber)
	}
	return observable
}

//jig:name ObservableObservable_WithLatestFromAll

// WithLatestFromAll flattens a higher order observable (e.g. ObservableObservable) by subscribing
// to all emitted observables (ie. Observable entries) until the source completes. It will then wait
// for all of the subscribed Observables to emit before emitting the first slice. The first
// observable that was emitted by the source will be used as the trigger observable. Whenever the
// trigger observable emits, a new slice will be emitted containing all the latest values.
func (o ObservableObservable) WithLatestFromAll() ObservableSlice {
	observable := func(observe SliceObserver, subscribeOn Scheduler, subscriber Subscriber) {
		observables := []Observable(nil)
		var observers struct {
			sync.Mutex
			assigned	[]bool
			values		[]interface{}
			initialized	int
			done		bool
		}
		makeObserver := func(index int) Observer {
			observer := func(next interface{}, err error, done bool) {
				observers.Lock()
				defer observers.Unlock()
				if !observers.done {
					switch {
					case !done:
						if !observers.assigned[index] {
							observers.assigned[index] = true
							observers.initialized++
						}
						observers.values[index] = next
						if index == 0 && observers.initialized == len(observers.values) {
							observe(observers.values, nil, false)
						}
					case err != nil:
						observers.done = true
						var zero []interface{}
						observe(zero, err, true)
					default:
						if index == 0 {
							observers.done = true
							var zero []interface{}
							observe(zero, nil, true)
						}
					}
				}
			}
			return observer
		}

		observer := func(next Observable, err error, done bool) {
			switch {
			case !done:
				observables = append(observables, next)
			case err != nil:
				var zero []interface{}
				observe(zero, err, true)
			default:
				subscribeOn.Schedule(func() {
					if subscriber.Subscribed() {
						numObservables := len(observables)
						observers.assigned = make([]bool, numObservables)
						observers.values = make([]interface{}, numObservables)
						for i, v := range observables {
							if !subscriber.Subscribed() {
								return
							}
							v(makeObserver(i), subscribeOn, subscriber)
						}
					}
				})
			}
		}
		o(observer, subscribeOn, subscriber)
	}
	return observable
}

//jig:name Observable_WithLatestFrom

// WithLatestFrom will subscribe to all Observables and wait for all of them to emit before emitting
// the first slice. The source observable determines the rate at which the values are emitted. The
// idea is that observables that are faster than the source, don't determine the rate at which the
// resulting observable emits. The observables that are combined with the source will be allowed to
// continue emitting but only will have their last emitted value emitted whenever the source emits.
func (o Observable) WithLatestFrom(other ...Observable) ObservableSlice {
	return FromObservable(append([]Observable{o}, other...)...).WithLatestFromAll()
}

//jig:name ObservableObserver

// ObservableObserver is a function that gets called whenever the Observable has
// something to report. The next argument is the item value that is only
// valid when the done argument is false. When done is true and the err
// argument is not nil, then the Observable has terminated with an error.
// When done is true and the err argument is nil, then the Observable has
// completed normally.
type ObservableObserver func(next Observable, err error, done bool)

//jig:name ObservableObservable

// ObservableObservable is a function taking an Observer, Scheduler and Subscriber.
// Calling it will subscribe the Observer to events from the Observable.
type ObservableObservable func(ObservableObserver, Scheduler, Subscriber)

//jig:name SliceObserver

// SliceObserver is a function that gets called whenever the Observable has
// something to report. The next argument is the item value that is only
// valid when the done argument is false. When done is true and the err
// argument is not nil, then the Observable has terminated with an error.
// When done is true and the err argument is nil, then the Observable has
// completed normally.
type SliceObserver func(next Slice, err error, done bool)

//jig:name ObservableSlice

// ObservableSlice is a function taking an Observer, Scheduler and Subscriber.
// Calling it will subscribe the Observer to events from the Observable.
type ObservableSlice func(SliceObserver, Scheduler, Subscriber)

//jig:name FromObservable

// FromObservable creates an ObservableObservable from multiple Observable values passed in.
func FromObservable(slice ...Observable) ObservableObservable {
	observable := func(observe ObservableObserver, scheduler Scheduler, subscriber Subscriber) {
		i := 0
		runner := scheduler.ScheduleRecursive(func(self func()) {
			if subscriber.Subscribed() {
				if i < len(slice) {
					observe(slice[i], nil, false)
					if subscriber.Subscribed() {
						i++
						self()
					}
				} else {
					var zero Observable
					observe(zero, nil, true)
				}
			}
		})
		subscriber.OnUnsubscribe(runner.Cancel)
	}
	return observable
}

//jig:name Observable_SubscribeOn

// SubscribeOn specifies the scheduler an Observable should use when it is
// subscribed to.
func (o Observable) SubscribeOn(scheduler Scheduler) Observable {
	observable := func(observe Observer, _ Scheduler, subscriber Subscriber) {
		if scheduler.IsConcurrent() {
			subscriber.OnWait(nil)
		} else {
			subscriber.OnWait(scheduler.Wait)
		}
		o(observe, scheduler, subscriber)
	}
	return observable
}

//jig:name ObservableSlice_Subscribe

// Subscribe operates upon the emissions and notifications from an Observable.
// This method returns a Subscription.
// Subscribe uses a trampoline scheduler created with scheduler.MakeTrampoline().
func (o ObservableSlice) Subscribe(observe SliceObserver, schedulers ...Scheduler) Subscription {
	subscriber := subscriber.New()
	schedulers = append(schedulers, scheduler.MakeTrampoline())
	observer := func(next Slice, err error, done bool) {
		if !done {
			observe(next, err, done)
		} else {
			var zero Slice
			observe(zero, err, true)
			subscriber.Done(err)
		}
	}
	if !schedulers[0].IsConcurrent() {
		subscriber.OnWait(schedulers[0].Wait)
	}
	o(observer, schedulers[0], subscriber)
	return subscriber
}
