// Code generated by jig; DO NOT EDIT.

//go:generate jig

package main

import (
	"sync"
	"sync/atomic"

	"github.com/reactivego/scheduler"
	"github.com/reactivego/subscriber"
	"github.com/reactivego/vibrant/gio"
)

//jig:name TypeGioFrameEvent

type FrameEvent = gio.FrameEvent

//jig:name ExtendGioObservableFrameEvent

// ExtendGioObservableFrameEvent converts a gio Observable to a local type so operators can be generated for it.
func ExtendGioObservableFrameEvent(o gio.ObservableFrameEvent) ObservableFrameEvent {
	observable := func(observe FrameEventObserver, scheduler scheduler.Scheduler, subscriber subscriber.Subscriber) {
		o(gio.FrameEventObserver(observe), scheduler, subscriber)
	}
	return observable
}

//jig:name TypeGioCallOp

type CallOp = gio.CallOp

//jig:name AliasGioObservableCallOp

type CallOpObserver = gio.CallOpObserver

type ObservableCallOp = gio.ObservableCallOp

// AliasGioObservableCallOp forces generation type alias ObservableCallOp for gio.ObservableCallOp.
func AliasGioObservableCallOp() {
	var o ObservableCallOp
	_ = gio.ObservableCallOp(o)
}

//jig:name Scheduler

// Scheduler is used to schedule tasks to support subscribing and observing.
type Scheduler = scheduler.Scheduler

//jig:name Subscriber

// Subscriber is an interface that can be passed in when subscribing to an
// Observable. It allows a set of observable subscriptions to be canceled
// from a single subscriber at the root of the subscription tree.
type Subscriber = subscriber.Subscriber

//jig:name BytesObserver

// BytesObserver is a function that gets called whenever the Observable has
// something to report. The next argument is the item value that is only
// valid when the done argument is false. When done is true and the err
// argument is not nil, then the Observable has terminated with an error.
// When done is true and the err argument is nil, then the Observable has
// completed normally.
type BytesObserver func(next []byte, err error, done bool)

//jig:name ObservableBytes

// ObservableBytes is a function taking an Observer, Scheduler and Subscriber.
// Calling it will subscribe the Observer to events from the Observable.
type ObservableBytes func(BytesObserver, Scheduler, Subscriber)

//jig:name FromBytes

// FromBytes creates an ObservableBytes from multiple []byte values passed in.
func FromBytes(slice ...[]byte) ObservableBytes {
	observable := func(observe BytesObserver, scheduler Scheduler, subscriber Subscriber) {
		i := 0
		runner := scheduler.ScheduleRecursive(func(self func()) {
			if subscriber.Subscribed() {
				if i < len(slice) {
					observe(slice[i], nil, false)
					if subscriber.Subscribed() {
						i++
						self()
					}
				} else {
					var zero []byte
					observe(zero, nil, true)
				}
			}
		})
		subscriber.OnUnsubscribe(runner.Cancel)
	}
	return observable
}

//jig:name FrameEventObserver

// FrameEventObserver is a function that gets called whenever the Observable has
// something to report. The next argument is the item value that is only
// valid when the done argument is false. When done is true and the err
// argument is not nil, then the Observable has terminated with an error.
// When done is true and the err argument is nil, then the Observable has
// completed normally.
type FrameEventObserver func(next FrameEvent, err error, done bool)

//jig:name ObservableFrameEvent

// ObservableFrameEvent is a function taking an Observer, Scheduler and Subscriber.
// Calling it will subscribe the Observer to events from the Observable.
type ObservableFrameEvent func(FrameEventObserver, Scheduler, Subscriber)

//jig:name ObservableBytes_SwitchMapCallOp

// SwitchMapCallOp transforms the items emitted by an ObservableBytes by applying a
// function to each item an returning an ObservableCallOp. In doing so, it behaves much like
// what used to be called FlatMap, except that whenever a new ObservableCallOp is emitted
// SwitchMap will unsubscribe from the previous ObservableCallOp and begin emitting items
// from the newly emitted one.
func (o ObservableBytes) SwitchMapCallOp(project func([]byte) ObservableCallOp) ObservableCallOp {
	return o.MapObservableCallOp(project).SwitchAll()
}

//jig:name ObservableBytes_MapObservableCallOp

// MapObservableCallOp transforms the items emitted by an ObservableBytes by applying a
// function to each item.
func (o ObservableBytes) MapObservableCallOp(project func([]byte) ObservableCallOp) ObservableObservableCallOp {
	observable := func(observe ObservableCallOpObserver, subscribeOn Scheduler, subscriber Subscriber) {
		observer := func(next []byte, err error, done bool) {
			var mapped ObservableCallOp
			if !done {
				mapped = project(next)
			}
			observe(mapped, err, done)
		}
		o(observer, subscribeOn, subscriber)
	}
	return observable
}

//jig:name ObservableFrameEvent_MapCallOp

// MapCallOp transforms the items emitted by an ObservableFrameEvent by applying a
// function to each item.
func (o ObservableFrameEvent) MapCallOp(project func(FrameEvent) CallOp) ObservableCallOp {
	observable := func(observe CallOpObserver, subscribeOn Scheduler, subscriber Subscriber) {
		observer := func(next FrameEvent, err error, done bool) {
			var mapped CallOp
			if !done {
				mapped = project(next)
			}
			observe(mapped, err, done)
		}
		o(observer, subscribeOn, subscriber)
	}
	return observable
}

//jig:name ObservableCallOpObserver

// ObservableCallOpObserver is a function that gets called whenever the Observable has
// something to report. The next argument is the item value that is only
// valid when the done argument is false. When done is true and the err
// argument is not nil, then the Observable has terminated with an error.
// When done is true and the err argument is nil, then the Observable has
// completed normally.
type ObservableCallOpObserver func(next ObservableCallOp, err error, done bool)

//jig:name ObservableObservableCallOp

// ObservableObservableCallOp is a function taking an Observer, Scheduler and Subscriber.
// Calling it will subscribe the Observer to events from the Observable.
type ObservableObservableCallOp func(ObservableCallOpObserver, Scheduler, Subscriber)

//jig:name LinkErrors

const (
	AlreadyDone		= RxError("already done")
	AlreadySubscribed	= RxError("already subscribed")
	AlreadyWaiting		= RxError("already waiting")
	RecursionNotAllowed	= RxError("recursion not allowed")
	StateTransitionFailed	= RxError("state transition faled")
)

//jig:name LinkEnums

// state
const (
	linkUnsubscribed	= iota
	linkSubscribing
	linkIdle
	linkBusy
	linkError	// done:error
	linkCanceled	// externally:canceled
	linkCompleting
	linkComplete	// done:complete
)

// callbackState
const (
	callbackNil	= iota
	settingCallback
	callbackSet
)

// callbackKind
const (
	linkCallbackOnComplete	= iota
	linkCancelOrCompleted
)

//jig:name linkCallOp

type linkCallOpObserver func(*linkCallOp, CallOp, error, bool)

type linkCallOp struct {
	observe		linkCallOpObserver
	state		int32
	callbackState	int32
	callbackKind	int
	callback	func()
	subscriber	Subscriber
}

func newInitialLinkCallOp() *linkCallOp {
	return &linkCallOp{state: linkCompleting, subscriber: subscriber.New()}
}

func newLinkCallOp(observe linkCallOpObserver, subscriber Subscriber) *linkCallOp {
	return &linkCallOp{
		observe:	observe,
		subscriber:	subscriber.Add(),
	}
}

func (o *linkCallOp) Observe(next CallOp, err error, done bool) error {
	if !atomic.CompareAndSwapInt32(&o.state, linkIdle, linkBusy) {
		if atomic.LoadInt32(&o.state) > linkBusy {
			return AlreadyDone
		}
		return RecursionNotAllowed
	}
	o.observe(o, next, err, done)
	if done {
		if err != nil {
			if !atomic.CompareAndSwapInt32(&o.state, linkBusy, linkError) {
				return StateTransitionFailed
			}
		} else {
			if !atomic.CompareAndSwapInt32(&o.state, linkBusy, linkCompleting) {
				return StateTransitionFailed
			}
		}
	} else {
		if !atomic.CompareAndSwapInt32(&o.state, linkBusy, linkIdle) {
			return StateTransitionFailed
		}
	}
	if atomic.LoadInt32(&o.callbackState) != callbackSet {
		return nil
	}
	if atomic.CompareAndSwapInt32(&o.state, linkCompleting, linkComplete) {
		o.callback()
	}
	if o.callbackKind == linkCancelOrCompleted {
		if atomic.CompareAndSwapInt32(&o.state, linkIdle, linkCanceled) {
			o.callback()
		}
	}
	return nil
}

func (o *linkCallOp) SubscribeTo(observable ObservableCallOp, scheduler Scheduler) error {
	if !atomic.CompareAndSwapInt32(&o.state, linkUnsubscribed, linkSubscribing) {
		return AlreadySubscribed
	}
	observer := func(next CallOp, err error, done bool) {
		o.Observe(next, err, done)
	}
	observable(observer, scheduler, o.subscriber)
	if !atomic.CompareAndSwapInt32(&o.state, linkSubscribing, linkIdle) {
		return StateTransitionFailed
	}
	return nil
}

func (o *linkCallOp) Cancel(callback func()) error {
	if !atomic.CompareAndSwapInt32(&o.callbackState, callbackNil, settingCallback) {
		return AlreadyWaiting
	}
	o.callbackKind = linkCancelOrCompleted
	o.callback = callback
	if !atomic.CompareAndSwapInt32(&o.callbackState, settingCallback, callbackSet) {
		return StateTransitionFailed
	}
	o.subscriber.Unsubscribe()
	if atomic.CompareAndSwapInt32(&o.state, linkCompleting, linkComplete) {
		o.callback()
	}
	if atomic.CompareAndSwapInt32(&o.state, linkIdle, linkCanceled) {
		o.callback()
	}
	return nil
}

func (o *linkCallOp) OnComplete(callback func()) error {
	if !atomic.CompareAndSwapInt32(&o.callbackState, callbackNil, settingCallback) {
		return AlreadyWaiting
	}
	o.callbackKind = linkCallbackOnComplete
	o.callback = callback
	if !atomic.CompareAndSwapInt32(&o.callbackState, settingCallback, callbackSet) {
		return StateTransitionFailed
	}
	if atomic.CompareAndSwapInt32(&o.state, linkCompleting, linkComplete) {
		o.callback()
	}
	return nil
}

//jig:name ObservableObservableCallOp_SwitchAll

// SwitchAll converts an Observable that emits Observables into a single Observable
// that emits the items emitted by the most-recently-emitted of those Observables.
func (o ObservableObservableCallOp) SwitchAll() ObservableCallOp {
	observable := func(observe CallOpObserver, subscribeOn Scheduler, subscriber Subscriber) {
		observer := func(link *linkCallOp, next CallOp, err error, done bool) {
			if !done || err != nil {
				observe(next, err, done)
			} else {
				link.subscriber.Unsubscribe()
			}
		}
		currentLink := newInitialLinkCallOp()
		var switcherMutex sync.Mutex
		switcherSubscriber := subscriber.Add()
		switcher := func(next ObservableCallOp, err error, done bool) {
			switch {
			case !done:
				previousLink := currentLink
				func() {
					switcherMutex.Lock()
					defer switcherMutex.Unlock()
					currentLink = newLinkCallOp(observer, subscriber)
				}()
				previousLink.Cancel(func() {
					switcherMutex.Lock()
					defer switcherMutex.Unlock()
					currentLink.SubscribeTo(next, subscribeOn)
				})
			case err != nil:
				currentLink.Cancel(func() {
					var zero CallOp
					observe(zero, err, true)
				})
				switcherSubscriber.Unsubscribe()
			default:
				currentLink.OnComplete(func() {
					var zero CallOp
					observe(zero, nil, true)
				})
				switcherSubscriber.Unsubscribe()
			}
		}
		o(switcher, subscribeOn, switcherSubscriber)
	}
	return observable
}

//jig:name RxError

type RxError string

func (e RxError) Error() string	{ return string(e) }
