// Code generated by jig; DO NOT EDIT.

//go:generate jig

package main

import (
	"github.com/reactivego/scheduler"
	"github.com/reactivego/subscriber"
	"github.com/reactivego/vibrant/gio"
)

//jig:name TypeGioFrameEvent

type FrameEvent = gio.FrameEvent

//jig:name ExtendGioObservableFrameEvent

// ExtendGioObservableFrameEvent converts a gio Observable to a local type so operators can be generated for it.
func ExtendGioObservableFrameEvent(o gio.ObservableFrameEvent) ObservableFrameEvent {
	observable := func(observe FrameEventObserver, scheduler scheduler.Scheduler, subscriber subscriber.Subscriber) {
		o(gio.FrameEventObserver(observe), scheduler, subscriber)
	}
	return observable
}

//jig:name TypeGioCallOp

type CallOp = gio.CallOp

//jig:name AliasGioObservableCallOp

type CallOpObserver = gio.CallOpObserver

type ObservableCallOp = gio.ObservableCallOp

// AliasGioObservableCallOp forces generation type alias ObservableCallOp for gio.ObservableCallOp.
func AliasGioObservableCallOp() {
	var o ObservableCallOp
	_ = gio.ObservableCallOp(o)
}

//jig:name Scheduler

// Scheduler is used to schedule tasks to support subscribing and observing.
type Scheduler = scheduler.Scheduler

//jig:name Subscriber

// Subscriber is an interface that can be passed in when subscribing to an
// Observable. It allows a set of observable subscriptions to be canceled
// from a single subscriber at the root of the subscription tree.
type Subscriber = subscriber.Subscriber

//jig:name FrameEventObserver

// FrameEventObserver is a function that gets called whenever the Observable has
// something to report. The next argument is the item value that is only
// valid when the done argument is false. When done is true and the err
// argument is not nil, then the Observable has terminated with an error.
// When done is true and the err argument is nil, then the Observable has
// completed normally.
type FrameEventObserver func(next FrameEvent, err error, done bool)

//jig:name ObservableFrameEvent

// ObservableFrameEvent is a function taking an Observer, Scheduler and Subscriber.
// Calling it will subscribe the Observer to events from the Observable.
type ObservableFrameEvent func(FrameEventObserver, Scheduler, Subscriber)

//jig:name ObservableFrameEvent_MapCallOp

// MapCallOp transforms the items emitted by an ObservableFrameEvent by applying a
// function to each item.
func (o ObservableFrameEvent) MapCallOp(project func(FrameEvent) CallOp) ObservableCallOp {
	observable := func(observe CallOpObserver, subscribeOn Scheduler, subscriber Subscriber) {
		observer := func(next FrameEvent, err error, done bool) {
			var mapped CallOp
			if !done {
				mapped = project(next)
			}
			observe(mapped, err, done)
		}
		o(observer, subscribeOn, subscriber)
	}
	return observable
}
